### ISSUE TITLE
UnboundLocalError at user signup

### ISSUE THREAD

**Issue by isoboroff** [isoboroff/submit-system#20]
When registering as a new user, I get the following:

Environment:

Request Method: POST
Request URL: http://127.0.0.1:8000/signup/

Django Version: 4.1.4
Python Version: 3.10.13
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'bootstrap5',
 'evalbase']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback (most recent call last):
  File "/Users/soboroff/submit-system/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/soboroff/submit-system/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/soboroff/submit-system/venv/lib/python3.10/site-packages/django/views/decorators/http.py", line 43, in inner
    return func(request, *args, **kwargs)
  File "/Users/soboroff/submit-system/evalbase/evalbase/views.py", line 35, in signup_view
    return render(request, 'evalbase/signup.html', context)

Exception Type: UnboundLocalError at /signup/
Exception Value: local variable 'context' referenced before assignment

**Comment by isoboroff** [comment]
I am not sure why the context block got dropped here
